# Generated by Django 4.2.7 on 2023-11-13 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_uomcategory_remove_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciepe',
            name='ingredients',
        ),
    ]
